### ISSUE TITLE
Server is doesn't get started

### ISSUE THREAD

**Issue by Lord-code** [jasielmacedo/steam-microtransaction-api#1]
Hello!
When I type in the console "npm start", I receive only this:

```
madpack@ubuntu:~/steam-microtransaction-api$ npm start

> steam-microtransaction-api@1.0.0 start /home/madpack/steam-microtransaction-api
> ts-node -r tsconfig-paths/register ./src/entrypoint.ts
```

Why don't I receive any logs, and when trying to check API Status, I get a 404 error?
The test "npm run test" passes without errors.

I will be glad of any help, thanks!

**Comment by Lord-code** [comment]
In the end, I wrote my own server...

**Comment by jasielmacedo** [comment]
the first initiation process is slow and delays a lot. the command was right but you need to wait until the initialization is finished.
