### ISSUE TITLE
In-game steam inventory purchase

### ISSUE THREAD

**Issue by Snipe3000** [jasielmacedo/steam-microtransaction-api#13]
Hello,

Our situation doesnt deal in individual items, but we still need to use steams microtransaction api found here: https://partner.steamgames.com/doc/features/microtransactions/recurring_billing

Would this project still allow us to do this? I'm a bit confused with the server side of things. Would we need to setup a steam inventory service? and how do we tie that into your api?

What we are looking for is a system that allows us to setup recurring billing, and then check the users billing standing in-game.

**Comment by VFerguson-haikurange** [comment]
As I dig into this project more and more, its seems to be outdated.
https://partner.steamgames.com/doc/webapi/ISteamMicroTxn#InitTxn
This InitPurchaseArgs in this library do not align at all. I'll see if I can update it to get a proper Init sent to steam.

**Comment by Snipe3000** [comment]
Change of plans, we are just going to try to get a simple in-game item purchase working with steam's Inventory services.

As I dig into this project more and more, its seems to be outdated.
https://partner.steamgames.com/doc/webapi/ISteamMicroTxn#InitTxn
The InitPurchaseArgs in this library do not align at all with steam's API. I'll see if I can update it to get a proper Init sent to steam.

**Comment by jasielmacedo** [comment]
@Snipe3000 I've updated the repo but I didn't find the outdated information that you mentioned. In fact this api doesn't include some optional fields, but all the required fields are there.
https://github.com/jasielmacedo/steam-microtransaction-api/blob/main/src/steam/steamrequest.ts#L86-L98
