### ISSUE TITLE
How the users pay for the item?

### ISSUE THREAD

**Issue by ChurikiTenna** [jasielmacedo/steam-microtransaction-api#14]
I have done these so far using cloud functions (not heroku).
1. The user (player) clicks on the UI product.
2. Your game calls the /InitPurchase endpoint to start the purchase.

However I have no clue how to implement this.
3. The game will display a confirmation dialog (inside the game).
4. The user buys the item (pays for it).

A payment overlay does not appear after successful InitPurchase

At here,
```
const data = await req.steam.steamMicrotransactionInitWithOneItem({
            appId,
            category,
            amount: product.price,
            itemDescription,
            itemId,
            orderId,
            steamId,
        });

        console.log('steam response', data.response.result)
```
I get the log:
`steam response OK`

I am very new to Steam, so please bear with me..

**Comment by AyanamiSean** [comment]
Hi @ChurikiTenna, did you solve the problem, I am new to Steam and seems I have met the same issue with your case, could you pls tell me how to fix it?
